export const TEMPLATE_DEFINITIONS = {
  current: {
    label: "目前情境",
    description: "目前設定的版本，含分期與補貼",
    basics: {
      startingTwd: 21010,
      jpyCashTwd: 18321,
      includeJpyCash: true,
      monthlySalary: 51070,
      salaryStartsOffset: 1,
      monthlySubsidy: 3600,
      subsidyStartsOffset: 0,
      monthlyRent: 15000,
      monthlyLivingCost: 15000,
      monthlyStudentLoan: 5001,
      monthsToProject: 7,
    },
    oneTimeItems: [
      { name: "應收款", amount: 2989, monthOffset: 0, type: "income", category: "other" },
      { name: "星展／凱基／聯邦小帳單", amount: 9599, monthOffset: 0, type: "expense", category: "tech" },
    ],
    installments: [
      { name: "玉山 3月帳單分期", principal: 14377, apr: 11, terms: 6, startOffset: 1 },
      { name: "國泰 4月帳單分期", principal: 11046, apr: 12, terms: 6, startOffset: 1 },
      { name: "玉山 4月帳單分期", principal: 35039, apr: 11, terms: 6, startOffset: 1 },
    ],
  },
  graduate: {
    label: "社會新鮮人",
    description: "低薪、含學貸、支出偏保守",
    basics: {
      startingTwd: 12000,
      jpyCashTwd: 0,
      includeJpyCash: false,
      monthlySalary: 36000,
      salaryStartsOffset: 0,
      monthlySubsidy: 0,
      subsidyStartsOffset: 0,
      monthlyRent: 9000,
      monthlyLivingCost: 12000,
      monthlyStudentLoan: 3200,
      monthsToProject: 12,
    },
    oneTimeItems: [
      { name: "入職體檢", amount: 2200, monthOffset: 0, type: "expense", category: "medical" },
    ],
    installments: [],
  },
  family: {
    label: "有小孩家庭",
    description: "生活成本高，含年支與教育費",
    basics: {
      startingTwd: 80000,
      jpyCashTwd: 0,
      includeJpyCash: false,
      monthlySalary: 92000,
      salaryStartsOffset: 0,
      monthlySubsidy: 5000,
      subsidyStartsOffset: 0,
      monthlyRent: 26000,
      monthlyLivingCost: 36000,
      monthlyStudentLoan: 0,
      monthsToProject: 12,
    },
    oneTimeItems: [
      { name: "暑期旅遊", amount: 28000, monthOffset: 2, type: "expense", category: "travel" },
      { name: "補習費", amount: 18000, monthOffset: 3, type: "expense", category: "social" },
    ],
    installments: [],
  },
  freelancer: {
    label: "自由工作者",
    description: "收入起伏大，固定成本較低",
    basics: {
      startingTwd: 45000,
      jpyCashTwd: 0,
      includeJpyCash: false,
      monthlySalary: 40000,
      salaryStartsOffset: 0,
      monthlySubsidy: 0,
      subsidyStartsOffset: 0,
      monthlyRent: 12000,
      monthlyLivingCost: 18000,
      monthlyStudentLoan: 0,
      monthsToProject: 10,
    },
    oneTimeItems: [
      { name: "案款尾款", amount: 25000, monthOffset: 1, type: "income", category: "other" },
      { name: "設備更新", amount: 32000, monthOffset: 4, type: "expense", category: "tech" },
    ],
    installments: [],
  },
};

export const TEMPLATE_OPTIONS = Object.entries(TEMPLATE_DEFINITIONS).map(([key, value]) => ({
  key,
  label: value.label,
}));
