export const TEMPLATE_DEFINITIONS = {
  current: {
    label: "空白情境",
    description: "從零開始填入你的收入與支出",
    basics: {
      startingTwd: 0,
      jpyCash: 0,
      includeJpyCash: false,
      monthlySalary: 0,
      salaryStartsOffset: 0,
      monthlySubsidy: 0,
      subsidyStartsOffset: 0,
      monthlyRent: 0,
      monthlyLivingCost: 0,
      monthlyStudentLoan: 0,
      monthsToProject: 12,
    },
    oneTimeItems: [],
    installments: [],
  },
  graduate: {
    label: "社會新鮮人",
    description: "低薪、含學貸、支出偏保守",
    basics: {
      startingTwd: 12000,
      jpyCash: 0,
      includeJpyCash: false,
      monthlySalary: 36000,
      salaryStartsOffset: 0,
      monthlySubsidy: 0,
      subsidyStartsOffset: 0,
      monthlyRent: 9000,
      monthlyLivingCost: 12000,
      monthlyStudentLoan: 3200,
      monthsToProject: 12,
    },
    oneTimeItems: [
      { name: "入職體檢", amount: 2200, monthOffset: 0, type: "expense", category: "medical" },
    ],
    installments: [],
  },
  family: {
    label: "有小孩家庭",
    description: "生活成本高，含年支與教育費",
    basics: {
      startingTwd: 80000,
      jpyCash: 0,
      includeJpyCash: false,
      monthlySalary: 92000,
      salaryStartsOffset: 0,
      monthlySubsidy: 5000,
      subsidyStartsOffset: 0,
      monthlyRent: 26000,
      monthlyLivingCost: 36000,
      monthlyStudentLoan: 0,
      monthsToProject: 12,
    },
    oneTimeItems: [
      { name: "暑期旅遊", amount: 28000, monthOffset: 2, type: "expense", category: "travel" },
      { name: "補習費", amount: 18000, monthOffset: 3, type: "expense", category: "social" },
    ],
    installments: [],
  },
  freelancer: {
    label: "自由工作者",
    description: "收入起伏大，固定成本較低",
    basics: {
      startingTwd: 45000,
      jpyCash: 0,
      includeJpyCash: false,
      monthlySalary: 40000,
      salaryStartsOffset: 0,
      monthlySubsidy: 0,
      subsidyStartsOffset: 0,
      monthlyRent: 12000,
      monthlyLivingCost: 18000,
      monthlyStudentLoan: 0,
      monthsToProject: 10,
    },
    oneTimeItems: [
      { name: "案款尾款", amount: 25000, monthOffset: 1, type: "income", category: "other" },
      { name: "設備更新", amount: 32000, monthOffset: 4, type: "expense", category: "tech" },
    ],
    installments: [],
  },
};

export const TEMPLATE_OPTIONS = Object.entries(TEMPLATE_DEFINITIONS).map(([key, value]) => ({
  key,
  label: value.label,
}));
